Flownative:
  Prometheus:
    metrics:

      # Number of HTTP requests processed by Flow
      # See: \Flownative\Prometheus\FlowMetrics\HttpMetricsCollectorComponent
      neos_flow_http_requests_total:
        type: "counter"
        help: "Number of HTTP requests processed by Flow\'s HTTP stack"
        labelNames: ["code"]

      # Number of Flow sessions
      # See: \Flownative\Prometheus\FlowMetrics\SessionMetricsCollectorService
      neos_flow_sessions:
        type: "gauge"
        help: "Number of Flow sessions"
        labelNames: ["state"]
