Neos:
  Flow:
    http:
      chain:
        'postprocess':
          chain:
            'Flownative.Prometheus:metricsExporter':
              'position': 'end'
              component: 'Flownative\Prometheus\FlowMetrics\HttpMetricsCollectorComponent'
              componentOptions: []
